actions: check out testing

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -14,7 +14,7 @@ jobs:
       date: ${{ steps.ts.outputs.DATE }}
     strategy:
       matrix:
-        build-type: [sweet]
+        build-type: [sweet, ginkgo, mi89x7]
         ksu-type: [zako, zako_susfs, none]
 
     steps:
@@ -38,14 +38,38 @@ jobs:
 
       - name: Preparing kernel sources
         run: |
-          if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
-            rm -rf android_kernel_xiaomi_sm6150
+          if [[ "${{ matrix.build-type }}" == "sweet" ]]; then
+            if [ -d "$PWD/android_kernel_xiaomi_sm6150" ]; then
+              rm -rf android_kernel_xiaomi_sm6150
+            fi
+            echo "Cloning kernel sources..."
+            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6150
+            echo "Copying buildscript..."
+            cp build.sh android_kernel_xiaomi_sm6150/
+            chmod +x ./android_kernel_xiaomi_sm6150/build.sh
+          elif [[ "${{ matrix.build-type }}" == "ginkgo" ]]; then
+            if [ -d "$PWD/android_kernel_xiaomi_sm6125" ]; then
+              rm -rf android_kernel_xiaomi_sm6125
+            fi
+            echo "Cloning kernel sources..."
+            git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6125
+            echo "Copying buildscript..."
+            cp build.sh android_kernel_xiaomi_sm6125/
+            chmod +x ./android_kernel_xiaomi_sm6125/build.sh
+          elif [[ "${{ matrix.build-type }}" == "mi89x7" ]]; then
+            if [ -d "$PWD/android_kernel_xiaomi_msm8937" ]; then
+              rm -rf android_kernel_xiaomi_msm8937
+            fi
+            echo "Cloning kernel sources..."
+            git clone https://github.com/LineageOS/android_kernel_xiaomi_msm8937.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_msm8937
+            echo "Copying buildscript..."
+            cp build.sh android_kernel_xiaomi_msm8937/
+            chmod +x ./android_kernel_xiaomi_msm8937/build.sh
+          else
+            echo "Invalid build type: ${{ matrix.build-type }}"
+            exit 1
           fi
-          echo "Cloning kernel sources..."
-          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6150.git -b "lineage-23.2" --depth=1 android_kernel_xiaomi_sm6150
-          echo "Copying buildscript..."
-          cp build.sh android_kernel_xiaomi_sm6150/
-          chmod +x ./android_kernel_xiaomi_sm6150/build.sh
+          
 
       - name: Compile the kernel
         run: |
@@ -63,12 +87,23 @@ jobs:
             echo "Invalid KSU type: ${{ matrix.ksu-type }}"
             exit 1
           fi
-          cd android_kernel_xiaomi_sm6150/
           echo "Starting to compile..."
           if [[ "${{ matrix.build-type }}" == "sweet" ]]; then
+            cd android_kernel_xiaomi_sm6150/
             ./build.sh sweet --ksu=$KSU_CHOICE
+            cd ..
+          elif [[ "${{ matrix.build-type }}" == "ginkgo" ]]; then
+            cd android_kernel_xiaomi_sm6125/
+            ./build.sh ginkgo --ksu=$KSU_CHOICE
+            cd ..
+          elif [[ "${{ matrix.build-type }}" == "mi89x7" ]]; then
+            cd android_kernel_xiaomi_msm8937/
+            ./build.sh mi89x7 --ksu=$KSU_CHOICE
+            cd ..
+          else
+            echo "Invalid build type: ${{ matrix.build-type }}"
+            exit 1
           fi
-          cd ..
 
       - name: Preparing AnyKernel3 sources
         run: |
@@ -76,14 +111,32 @@ jobs:
             rm -rf AnyKernel3
           fi
           git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
-          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
-          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
-          cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
           if [[ "${{ matrix.build-type }}" == "sweet" ]]; then
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/Image.gz AnyKernel3/
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtb.img AnyKernel3/
+            cp android_kernel_xiaomi_sm6150/out/arch/arm64/boot/dtbo.img AnyKernel3/
             sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
             sed -i 's/device.name1=sweet/device.name1=sweet/' AnyKernel3/anykernel.sh
             sed -i 's/device.name2=sweetin/device.name2=sweetin/' AnyKernel3/anykernel.sh
             sed -i 's/sweet (sm6150)/sweet (sm6150)/g' AnyKernel3/banner
+          elif [[ "${{ matrix.build-type }}" == "ginkgo" ]]; then
+            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/Image.gz AnyKernel3/
+            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtb.img AnyKernel3/
+            cp android_kernel_xiaomi_sm6125/out/arch/arm64/boot/dtbo.img AnyKernel3/
+            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/
+            sed -i 's/device.name1=sweet/device.name1=ginkgo/' AnyKernel3/anykernel.sh
+            sed -i 's/device.name2=sweetin/device.name2=willow/' AnyKernel3/anykernel.sh
+            sed -i 's/sweet (sm6150)/ginkgo (sm6125)/g' AnyKernel3/banner
+          elif [[ "${{ matrix.build-type }}" == "mi89x7" ]]; then
+            cp android_kernel_xiaomi_msm8937/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
+            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
+            sed -i 's/device.name1=sweet/device.name1=mi8937/' AnyKernel3/anykernel.sh
+            sed -i 's/device.name2=sweetin/device.name2=mi8917/' AnyKernel3/anykernel.sh
+            sed -i '/device.name2=mi8917/a device.name3=santoni\ndevice.name4=prada\ndevice.name5=rolex\ndevice.name6=ugglite\ndevice.name7=riva\ndevice.name8=ugg' AnyKernel3/anykernel.sh
+            sed -i 's/sweet (sm6150)/mi8937 (msm8937)/g' AnyKernel3/banner
+          else
+            echo "Invalid build type: ${{ matrix.build-type }}"
+            exit 1
           fi
 
       - name: Pack & upload artifacts (All builds)
